version: '3.1'
services:
  database:
    container_name: api
    image: postgres
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER : root
      POSTGRES_PASSWORD: toor
      POSTGRES_DB: postgres
    ports:
      - "5431:5432"
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d